# Site settings
title: "Agustinus Kristiadi's Blog"
header-img: "img/home-bg.jpg"
email: "kristiadi7@gmail.com"
description: ""
baseurl: ""
url: "http://wiseodd.github.io"
github_username: "wiseodd"

# Build settings
markdown: "kramdown"
highlighter: "rouge"
permalink: "pretty"
paginate: 10
timezone: "Europe/Berlin"
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
plugins: ["jekyll-paginate", "jekyll-sitemap"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
